### ISSUE TITLE
Unable run app in local machine 

### ISSUE THREAD

**Issue by gowthaman-i2i** [formio/ngFormBuilder#335]
```
gowthaman@gowthaman-i2i:~/ideas2it/Form IO/Render-Form/ngFormBuilder$ gulp
[11:09:07] Using gulpfile ~/ideas2it/Form IO/Render-Form/ngFormBuilder/gulpfile.js
[11:09:07] Starting 'build'...
[11:09:07] Starting 'clean'...
[11:09:07] Starting 'watch'...
[11:09:07] Finished 'clean' after 134 ms
[11:09:07] Starting 'scripts:basic'...
[11:09:07] Starting 'scripts:complete'...
[11:09:07] Starting 'scripts:full'...
1146089 bytes written (9.70 seconds)
[11:09:19] /home/gowthaman/ideas2it/Form IO/Render-Form/ngFormBuilder/dist/ngFormBuilder.min.js reloaded.
[11:09:19] Finished 'watch' after 12 s
[11:09:20] /home/gowthaman/ideas2it/Form IO/Render-Form/ngFormBuilder/dist/ngFormBuilder.min.js reloaded.
[11:09:20] Finished 'scripts:basic' after 13 s
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'lodash/isNAN' from '/home/gowthaman/ideas2it/Form IO/Render-Form/ngFormBuilder/node_modules/ng-formio/src/directives'
    at /home/gowthaman/ideas2it/Form IO/Render-Form/ngFormBuilder/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/gowthaman/ideas2it/Form IO/Render-Form/ngFormBuilder/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/gowthaman/ideas2it/Form IO/Render-Form/ngFormBuilder/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/gowthaman/ideas2it/Form IO/Render-Form/ngFormBuilder/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/gowthaman/ideas2it/Form IO/Render-Form/ngFormBuilder/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/gowthaman/ideas2it/Form IO/Render-Form/ngFormBuilder/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```
below versions are installed 

```
$  node -v && npm -v && bower -v && gulp -v

v6.11.2
5.3.0
1.8.0
[11:12:28] CLI version 3.9.1
[11:12:28] Local version 3.9.1

````

**Comment by anupriya7295** [comment]
isNaN under lodash library is used by formioWizard script in ngFormio library which is used by ngFormioBuilder .Recent release of ngFormio using lodash version 4.17.4 ,which is not having isNAN.js ,To avoid this issue please use ngFormio version ,which is using lodash version having isNAN

**Comment by CatBakun** [comment]
I don't understand what version of nfFormio needs to be used on order to avoid this error. Can you specify?

**Comment by anupriyaideas2it** [comment]
It is enough to include lodash version in ngFormioBuilder having isNAN.js .Kindly refer [lodash](https://github.com/lodash/lodash) releases (for example: 4.17.3)
